version: '3'
services:
  mariadb:
    image: "mariadb:11"
    ports:
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
