version: '3'
services:
  mysql56:
    image: "mysql:5.6"
    ports:
      - 3306:3306
    volumes: 
      - ./data56:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql57:
    image: "mysql:5.7"
    ports:
      - 3307:3306
    volumes: 
      - ./data57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql8:
    image: "mysql:8"
    ports:
      - 3308:3306
    volumes: 
      - ./data8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}