version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest # Replace with the correct image name if different
    container_name: ollama-backend
    ports:
      - "11434:11434" # Expose Ollama's default API port
    volumes:
      - ./ollama_data:/data # Persistent storage for models and data

  webui:
    image: your-webui-image:latest # Replace with your WebUI Docker image
    container_name: ollama-webui
    ports:
      - "3000:3000" # Expose the WebUI on port 3000
    environment:
      - REACT_APP_BACKEND_URL=http://ollama-backend:11434
    depends_on:
      - ollama

volumes:
  ollama_data:
    driver: local