version: '3'
services:
  postgres16:
    image: "postgres:16"
    ports: 
      - 5432:5432
    volumes:
      - ./postgres14:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - 5800:80
    volumes: 
      # pgAdmin runs as the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050) in the container
      # sudo chown -R 5050:5050 pgadmin
      - ${DATA_PATH_HOST}/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres16
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
